name: Cargo Fmt / Clippy / Build

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  lockfile:
    name: Ensure lockfile is up-to-date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly && rustup default nightly
      - run: cargo update --locked

  rustfmt:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup update nightly && rustup default nightly
    - run: rustup component add rustfmt
    - run: cargo fmt --all --check

  clippy:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly && rustup default nightly
      - run: rustup component add rust-src
      - run: rustup component add clippy
      - run: cargo clippy --locked --workspace --all-features --no-deps --keep-going --target riscv64imac-unknown-none-elf

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly && rustup default nightly
      - run: rustup component add rust-src
      - run: cargo build --target riscv64imac-unknown-none-elf
