name: Cargo command

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  rust:
    name: Install && Update Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly && rustup default nightly
      - name: Display Cargo version
        run: cargo --version
      - name: Display Rustc version
        run: rustc --version

  lockfile:
    name: Lockfile
    runs-on: ubuntu-latest
    needs: rust
    steps:
      - uses: actions/checkout@v4
      - name: Check update
        run: cargo update --locked

  rustfmt:
    name: Fmt
    runs-on: ubuntu-latest
    needs: rust
    steps:
      - uses: actions/checkout@v4
      - name: Install rustfmt component
        run: rustup component add rustfmt
      - name: Check format
        run: cargo fmt --all --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    needs: rust
    steps:
      - uses: actions/checkout@v4
      - name: Install rust-src and clippy components
        run: rustup component add rust-src clippy
      - name: Check clippy
        run: cargo clippy --locked --workspace --all-features --no-deps --keep-going --target riscv64imac-unknown-none-elf

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: rust
    steps:
      - uses: actions/checkout@v4
      - name: Install rust-src component
        run: rustup component add rust-src
      - name: Build on riscv64imac-unknown-none-elf target
        run: cargo build --target riscv64imac-unknown-none-elf
