name: Deploy mdBook

on:
  push:
    branches: ["main"]
    paths: ['doc/book/**']
  pull_request:
    branches: ["main"]
    paths: ['doc/book/**']

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build mdBook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - name: Install mdBook
        run: cargo install mdbook --no-default-features --features search --locked
      - name: Display mdBook version
        run: mdbook --version
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build the mdBook
        run: cd ./doc/book; mdbook build
      - name: Upload book artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./doc/book/book/

  deploy:
    name: Deploy book to Github Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
